export const GET_EMPLOYEES='GET_EMPLOYEES'
export const GET_EMPLOYEE='GET_EMPLOYEE'
export const POST_EMPLOYEES='POST_EMPLOYEES'
export const UPDATE_EMPLOYEES='UPDATE_EMPLOYEES'
export const DELETE_EMPLOYEES='DELETE_EMPLOYEES'
export const SET_CURRENT = 'SET_CURRENT' 
export const CLEAR_CURRENT = 'CLEAR_CURRENT' 

export const GET_DEPARTMENTS = 'GET_DEPARTMENTS'

export const GET_POSITIONS = 'GET_POSITIONS' 